# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to='login_reg.User')),
                ('user_favorites', models.ManyToManyField(related_name='user_favorites', to='login_reg.User')),
            ],
        ),
    ]
